apiVersion: v2
name: onecx-notification-ui
version: 0.0.0
description: notification UI
home: https://github.com/onecx/onecx-notification-ui
keywords:
  - notification
sources:
  - https://github.com/onecx/onecx-notification-ui
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
