app:
  name: ui
  image:
    repository: 'onecx-apps/onecx-notification-ui'
  routing:
    enabled: true
    path: /mfe/notification/
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OneCXNotificationModule'
          description: 'OneCX Notification UI'
          note: 'OneCX Notification UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-notification
          tagName: ocx-notification-component
        notification-connector:
          exposedModule: "./NotificationConnectorComponent"
          description: "Provides notification connection"
          type: COMPONENT
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-notification
          tagName: ocx-notification-connector-component
    # Microservice
    microservice:
      spec:
        name: OneCX Notification UI
        description: OneCX Notification Frontend
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
        # ACTION P: Adjust permissions for the entity
